name: social_share_kit_example
description: Demonstrates how to use the social_share_kit plugin.

publish_to: 'none'

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  social_share_kit:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  path_provider: ^2.0.11
  very_good_analysis: ^3.0.1

flutter:
  uses-material-design: true
  assets:
   - assets/spacex-unsplash.jpg
